version: "3"
services:
  etcd:
    image: bitnami/etcd:3.4.13
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
  web1:
    image: openresty/openresty:1.19.3.1-alpine
    volumes:
      - ./upstream/web1.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9001:80/tcp"
  web2:
    image: openresty/openresty:1.19.3.1-alpine
    volumes:
      - ./upstream/web2.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9002:80/tcp"