version: "3"
services:
  web1:
    image: nginx:1.18.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9001:80/tcp"
  web2:
    image: nginx:1.18.0-alpine
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9002:80/tcp"